"""
Invoice model — generated by Manager.
"""
from sqlalchemy import Column, Integer, String, Enum, DateTime, Date, Numeric, ForeignKey, func
from app.database import Base


class Invoice(Base):
    __tablename__ = "invoices"

    inv_id = Column(Integer, primary_key=True, autoincrement=True)
    order_id = Column(Integer, ForeignKey("orders.order_id"), nullable=False)
    cust_id = Column(Integer, ForeignKey("customers.cust_id"), nullable=False)
    payment_id = Column(Integer, ForeignKey("payments.payment_id", use_alter=True, name="fk_invoice_payment"), nullable=True)
    invoice_number = Column(String(50), unique=True, nullable=False)
    invoice_date = Column(Date, nullable=True)
    total_amount = Column(Numeric(10, 2), nullable=False, default=0)
    tax_amount = Column(Numeric(10, 2), nullable=False, default=0)
    final_amount = Column(Numeric(10, 2), nullable=False, default=0)
    invoice_status = Column(
        Enum("draft", "issued", "paid", "overdue", "cancelled", name="invoice_status"),
        default="draft",
        server_default="draft",
    )
    generated_by = Column(Integer, ForeignKey("users.user_id"), nullable=True)
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())
